"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const products_1 = require("../../controllers/products");
const router = (0, express_1.Router)();
router.get('/', products_1.productControllers.findAll);
router.get('/detail/:productId', products_1.productControllers.findOne);
router.post('/', products_1.productControllers.create);
router.patch('/', products_1.productControllers.update);
router.delete('/:productId', products_1.productControllers.remove);
exports.default = router;
